### ISSUE TITLE
Bug: interned = obj at QPA2/lib/intern.gi:13

### ISSUE THREAD

**Issue by heiderich** [oysteins/QPA2#16]
When if a file `~/qpa2_bug.g` consists of the following code block

```
LoadPackage("QPA");

LoadPackage("RingsForHomalg");
Q := HomalgFieldOfRationals( );

q := RightQuiver( "q(u,v,w)[a:u->v,b:v->u,c:v->u,d:v->w]" );

f := RightQuiver( "f(1)[t:1->1]" );
g := RightQuiver( "g(1)[]" );
Qf := PathAlgebra(Q,f);
Qg := PathAlgebra(Q,g);
Qf_tensor_Qg := TensorProductOfAlgebras( Qf, Qg );
```

then executing `gap ~/qpa2_bug.g` leads to the following error:

```
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `=' on 2 arguments at /home/florian/gap-4.9.0/lib/methsel2.g:250 called from
interned = obj at /home/florian/gap-4.9.0/pkg/QPA2/lib/intern.gi:13 called from
Intern( A ) at /home/florian/gap-4.9.0/pkg/QPA2/lib/algebra.gi:514 called from
PathAlgebra( LeftActingDomain( A ), OppositeQuiver( QuiverOfAlgebra( A ) ) ) at /home/florian/gap-4.9.0/pkg/QPA2/lib/algebra.gi:865 called from
OppositeAlgebra( A ) at /home/florian/gap-4.9.0/pkg/QPA2/lib/algebra.gi:892 called from
A ^ LEFT at /home/florian/gap-4.9.0/pkg/QPA2/lib/algebra.gi:965 called from
...  at /home/florian/qpa2_bug.g:12
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
```

When replacing the content of `~/qpa2_bug.g` by

1. a version including a garbage collection

```
LoadPackage("QPA");
LoadPackage("RingsForHomalg");
Q := HomalgFieldOfRationals( );

q := RightQuiver( "q(u,v,w)[a:u->v,b:v->u,c:v->u,d:v->w]" );
q := 1;
GASMAN("collect");

f := RightQuiver( "f(1)[t:1->1]" );
g := RightQuiver( "g(1)[]" );
Qf := PathAlgebra(Q,f);
Qg := PathAlgebra(Q,g);
Qf_tensor_Qg := TensorProductOfAlgebras( Qf, Qg );
```

or

2. a version not using `RingsForHomalg`

```
LoadPackage("QPA");

Q := Rationals;

q := RightQuiver( "q(u,v,w)[a:u->v,b:v->u,c:v->u,d:v->w]" );

f := RightQuiver( "f(1)[t:1->1]" );
g := RightQuiver( "g(1)[]" );
Qf := PathAlgebra(Q,f);
Qg := PathAlgebra(Q,g);
Qf_tensor_Qg := TensorProductOfAlgebras( Qf, Qg );

```

or

3. a version with a different name `qq` instead of `q` for the quiver

```
LoadPackage("QPA");

LoadPackage("RingsForHomalg");
Q := HomalgFieldOfRationals( );

q := RightQuiver( "qq(u,v,w)[a:u->v,b:v->u,c:v->u,d:v->w]" );

f := RightQuiver( "f(1)[t:1->1]" );
g := RightQuiver( "g(1)[]" );
Qf := PathAlgebra(Q,f);
Qg := PathAlgebra(Q,g);
Qf_tensor_Qg := TensorProductOfAlgebras( Qf, Qg );

```

no error occurs.

Could this be related to caching, @sebasguts?

A workaround seems to be to replace line 

`     if interned <> fail and interned = obj then`

in `QPA2/lib/intern.gi` by

`     if interned <> fail and IsIdenticalObj(interned, obj) then`,

but I guess there must be a reason for using `=` and installing the method for `=` at the end of `QPA2/lib/intern.gi`.

**Comment by zickgraf** [comment]
I did some more investigation and if I understand the code correctly, the culprit is the caching mechanism, but not the on in `ToolsForHomalg` but the one in `QPA2` itself:

As I understand it, the method `Intern` in `lib/inter.gi` applied to an arbitrary object `obj` tries to find `obj` in `INTERN_HASH_TABLE`. To do this, it compares `obj` to entries of `INTERN_HASH_TABLE` using `=`. However, `obj` does not lie in the filter `IsIntered` yet, so the fallback definition of `=` in line 33 does not apply.
Two solutions I can think of (although I'm not sure if these are real solutions because I do not know the overall picture):

* call `SetFilterObj( obj, IsInterned );` before the comparisons (currently it's called after the comparisons)
* install `=` for `[ IsInterned, IsObject ]` instead of `[ IsInterned, IsIntered ]`

**Comment by oysteins** [comment]
It is correct that this is related to the caching (or interning) done by QPA in `lib/intern.gi`.  The solutions suggested by @zickgraf are, however, not appropriate, since they would destroy the interning mechanism.

Let me explain how the interning works and why it is there.

For certain objects, we want to make sure that there are no duplicates.  That is, we do not want to have objects that are equal (with respect to the `=` operation) but not the same object.  We "intern" objects to make sure that no duplicates exist.  The call `Intern( obj )` returns the unique interned object which is equal to `obj`.  The intention is that after the call to `Intern`, all references to `obj` should be thrown away, and the object returned by `Intern` should be used instead.

The interning mechanism keeps track of objects that have already been interned (using the hash table you found).  When `Intern` is called on an object `obj`, it does this:

1. Checks if there exists an interned object equal to `obj`, and if so, returns it.  If no such object exists:
2. Adds the object `obj` to the hash table of interned objects, modifies `obj` to have the filter `IsInterned` set, and returns it.

The result is that for interned objects, equality comparison can be done safely by using `IsIdenticalObj`, since we have ensured that there are no duplicates.

(The name "intern" and the associated functionality comes from Lisp, where [`INTERN`](http://www.lispworks.com/documentation/HyperSpec/Body/f_intern.htm#intern) is used to make symbol objects unique.)

So why do we have this in QPA?  There are a few situations where it is dangerous to have multiple objects which are equal to each other.  The most important one is for algebras, which are used to create categories of representations.

It is easy to create the same algebra twice:

```
Q := LeftQuiver( "Q(2)[a:1->2]" );
A1 := PathAlgebra( Q, Rationals );
A2 := PathAlgebra( Q, Rationals );
```

Now, without the interning mechanism, the algebras `A1` and `A2` would be equal but not identical:

```
gap> A1 = A2;
true
gap> IsIdenticalObj( A1, A2 );
false
```

This in itself is not a problem, but it becomes a problem when we create the category of representations over the algebra:

```
cat1 := CategoryOfQuiverRepresentations( A1 );
cat2 := CategoryOfQuiverRepresentations( A2 );
```

Since `CategoryOfQuiverRepresentations` is an attribute and the algebras store their attributes, we never recreate the category of representations by calling `CategoryOfQuiverRepresentations` multiple times on a single object.  But we do recreate it by calling `CategoryOfQuiverRepresentations` on the algebra `A1` and `A2` that are equal but not identical.  This leads to all sorts of problems.  Say that we create a representation `R1` over `A1` and a representation `R2` over `A2`.  Now these are representations over the same algebra, but they belong to different categories, and therefore we are unable to create a morphism from `R1` to `R2`.

To avoid all these problems, we call `Intern` in the constructor for algebras.  This ensures that even if we do create the same algebra twice, we will still end up with only one object.

**Comment by oysteins** [comment]
In the previous comment, I wrote a lot about the context where the bug appears (the `Intern` function), but not about the actual cause of the bug.

The cause of the bug is that some objects (namely, quivers and quiver algebras) are not comparable by `\=`, and this is again caused by my stupid use of GAP's family objects.  I believe I have fixed the bug, and will push my fix in a moment.

**Comment by zickgraf** [comment]
Thanks for the thorough explanation, now I understand this much better!

**Comment by heiderich** [comment]
Thank you very much for the quick fix!
