### ISSUE TITLE
Dependency from Polycyclic?

### ISSUE THREAD

**Issue by heiderich** [oysteins/QPA2#19]
QPA2 uses the function `IsIdentityMat`, but does not install it. It is installed in the package `Polycyclic`, which is loaded by default by GAP 4.9.3. However, when starting GAP with `SetUserPreference("PackagesToLoad", [ ]);` in `~/.gap/gap.ini`, then `LoadPackage("QPA")` throws the following warning:

```
Syntax warning: Unbound global variable in /home/gap/.gap/pkg/QPA2/lib/matrix.\
gi:27
  if IsIdentityMat( M ) then
```

Therefore I suggest to add the packages QPA2 depends on explicitly in `PackageInfo.g`. Maybe this includes `Polycyclic`. At least this error does not appear when first loading `Polycyclic`.

**Comment by oysteins** [comment]
Thank you for reporting this.  I had no idea that `IsIdentityMat` was defined in a package.  When writing the code that calls it, I probably just checked in a GAP session whether such a function existed, and then used it.  We don't really use the Polycyclic package (except for calling this one function), so instead of adding it as a dependency, I think it is better to avoid calling `IsIdentityMat`.  I will push a fix for this soon.

**Comment by heiderich** [comment]
That seems even better. Thank you!
