### ISSUE TITLE
Order of multiplication in a quiver algebra

### ISSUE THREAD

**Issue by sebastianpos** [oysteins/QPA2#22]
If I understand correctly, there is a function `ComposePaths` that enables me to compute the composite of paths in source-to-target order regardless of the underlying quiver being a left or right quiver. For me, this is nice since it lets me write my code in a way such that I don't have to check whether the underlying quiver with which I am working is a left or right quiver.

Would it be sensible to have an analogous operation for elements in the filter `IsQuiverAlgebraElement` that lets me perform multiplication in the corresponding path algebra in source-to-target order regardless of the type of underlying quiver? So far, I have to distinguish the case whether the underlying quiver is left or right, an depending on that, call the multiplication operation `*` with the arguments in appropriate order. Something like `MultiplyElementsInSourceToTargetOrder` would be very nice.

**Comment by oysteins** [comment]
I'm adding such a function now.  I call it `ComposeElements` by analogy with `ComposePaths`.

Depending on what you are doing, it might be even easier to just stick with one type of quiver (either left or right) and ignore the other type.  I introduced the concepts of left and right quivers in QPA2<sup>1</sup> since there are these two different conventions for how paths in a quiver are multiplied, where both are widely used and none of them obviously better than the other.  But QPA is intended for everyone who works with path algebras.  If you are writing for a subset of these who can agree on the same convention for path multiplication, or even better, for people who don't have strong opinions on this at all, then I think it could be sensible to just use one type of quiver exclusively.

On the other hand, if you do want to have both types of quivers, the `ComposeElements` functions is there for you to enjoy.  (And please let me know if other similar functions are needed.)

 * * *

<sup>1</sup> In QPA version 1 there is only one type of quiver -- the one I call "right quiver".

**Comment by sebastianpos** [comment]
Thank you very much.
I think I would like to support both types of quivers for convenience. If I want to work with quivers that appear in some paper, I would like to be able to directly type them into the system, without any conversion of the multiplication convention.
